apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dynamic
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: dynamic - project
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/argoproj/argo.git
    - https://github.com/ofirshtrull/argocd-preview.git
