apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user2
  namespace: argocd
  labels:
    group: user2
spec:
  project: dynamic
  source:
    repoURL: https://github.com/ofirshtrull/argocd-preview.git
    path: charts/app-of-apps
    targetRevision: master
    helm:
      values: |
        fullnameOverride: user2
        apps:
          backend:
            enabled: true
          frontend:
            enabled: true
  destination:
    namespace: user2
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

