apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
spec:
  source:
    helm:
      values: |
        replicaCount: 1
        image:
          tag: 'latest'
  # destination:
  #   namespace: "aaaa"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
