apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  source:
    helm:
      values: |
        replicaCount: 1
        image:
          tag: 'latest'

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
