apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-1-backend
  namespace: argocd
spec:
  project: dynamic
  destination:
    namespace: "user-1"
    server: "https://kubernetes.default.svc"
  source:
    path: charts/backend
    repoURL: "https://github.com/ofirshtrull/argocd-preview.git"
    targetRevision: master
    helm:
      values: |
        replicaCount: 1
        image:
          tag: 'latest'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-1-frontend
  namespace: argocd
spec:
  project: dynamic
  destination:
    namespace: "user-2"
    server: "https://kubernetes.default.svc"
  source:
    path: charts/backend
    repoURL: "https://github.com/ofirshtrull/argocd-preview.git"
    targetRevision: master
    helm:
      values: |
        replicaCount: 1
        image:
          tag: 'latest'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
