apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-2-backend
  namespace: argocd
spec:
  project: dynamic
  destination:
    namespace: "user-2"
  source:
    helm:
      values: |
        replicaCount: 1
        image:
          tag: 'latest'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-2-frontend
  namespace: argocd
spec:
  project: dynamic
  destination:
    namespace: "user-2"
  source:
    helm:
      values: |
        replicaCount: 1
        image:
          tag: 'latest'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
