{{- if .Values.apps.backend.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "app-of-apps.fullname" . }}-backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: {{ include "app-of-apps.fullname" . }}
    server: "https://104.198.143.103"
  source:
    path: charts/backend-rollouts
    repoURL: "https://github.com/ofirshtrull/argocd-preview.git"
    targetRevision: master
    helm:
      values: |
        replicaCount: 1
        image:
          tag: 'blue'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
