{{- if .Values.apps.frontend.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "app-of-apps.name" . }}-frontend
  namespace: argocd
spec:
  project: dynamic
  destination:
    namespace: {{ include "app-of-apps.name" . }}
    server: "https://kubernetes.default.svc"
  source:
    path: charts/frontend
    repoURL: "https://github.com/ofirshtrull/argocd-preview.git"
    targetRevision: master
    helm:
      values: |
        replicaCount: 1
        image:
          tag: 'latest'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
