apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    group: argocd
spec:
  project: dynamic
  source:
    repoURL: https://github.com/ofirshtrull/argocd-preview.git
    path: argo/app-of-apps/envs/helm
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
